name: Update images.json

on:
  push:
    paths:
      - 'docs/images/**'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          cd docs/images
          ls -1 *.jpg *.jpeg *.png 2>/dev/null | jq -R . | jq -s . > ../images.json

      - name: Commit and push images.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/images.json
          git commit -m "Update images.json" || echo "No changes"
          git push
